project_id = ""

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions.vdocipher-otp]
enabled = true
verify_jwt = false
import_map = "./functions/vdocipher-otp/deno.json"
entrypoint = "./functions/vdocipher-otp/index.ts"

[functions.fanbases-customer]
enabled = true
verify_jwt = false
import_map = "./functions/fanbases-customer/deno.json"
entrypoint = "./functions/fanbases-customer/index.ts"

[functions.fanbases-charge]
enabled = true
verify_jwt = false
import_map = "./functions/fanbases-charge/deno.json"
entrypoint = "./functions/fanbases-charge/index.ts"

[functions.fanbases-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/fanbases-webhook/deno.json"
entrypoint = "./functions/fanbases-webhook/index.ts"

[functions.fanbases-checkout]
enabled = true
verify_jwt = false
import_map = "./functions/fanbases-checkout/deno.json"
entrypoint = "./functions/fanbases-checkout/index.ts"
